POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "gsd another another new blog to test if user binds",
    "author": "gaba wabadsaf",
    "url": "funnny.com",
    "likes": 54254,
    "userId": "63a4ed6cfb899cbd823ab813"
}

###
GET http://localhost:3003/api/blogs

###
PUT http://localhost:3003/api/blogs/63a0a1e0fda06bb6c247c5eb HTTP/1.1
content-type: application/json 

{
    "title": "cool article",
    "author": "poopy funny face",
    "url": "cool.com",
    "likes": 545
}

###
PUT http://localhost:3003/api/blogs/1244 HTTP/1.1
content-type: application/json 

{
    "title": "cool article",
    "author": "poopy funny face",
    "url": "cool.com",
    "likes": 545
}

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "tjk",
    "name": "ted",
    "password": "funnyepicmoments12!"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "tjk",
    "password": "funnyepicmoments12!"
}
###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRqayIsImlkIjoiNjNhNTFjNWY5NTJjZDc2MGJjNDA1NWY4IiwiaWF0IjoxNjcxODI0ODE5fQ.FSK79QuXy__JIkFV4VKZN0YRsZr6oT1Bh6A7Izic_ps

{
    "title": "King Richard",
    "author": "gaba wabadsaf",
    "url": "funnny.com",
    "likes": 54254,
    "userId": "63a4ed6cfb899cbd823ab813"
}

###
DELETE http://localhost:3003/api/blogs/63a62c767668d50e6858f202
content-type: application/application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRqayIsImlkIjoiNjNhNTFjNWY5NTJjZDc2MGJjNDA1NWY4IiwiaWF0IjoxNjcxODM3MTQwfQ.Hvb924aDW3Bbm3I1Obwjt90V3bpFw332Lhv_5nlu9tM
